### ISSUE TITLE
Undefined method `valid_password?` for User

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#194] opened 2018-08-26 23:52 UTC
Localhost dev can get into a state where you can't log in. This predates updating Authlogic recently.

<img width="1090" alt="screenshot 2018-08-26 17 51 01" src="https://user-images.githubusercontent.com/472/44634581-e7df5b80-a99b-11e8-90d3-6fd0c70004aa.png">

**Comment by innatewonderer** [comment] 2018-09-04 03:04
I was able to reproduce similar error on login with `admin` credentials (from README). Never for `logout`. Then at some point, it stopped. Unable to reproduce :/ Do you have anything to help me reproduce this error?

**Comment by sudara** [comment] 2018-09-04 12:56
I'm not sure how to reproduce. Restarting rails usually fixes... I'll keep my eyes open...

**Comment by innatewonderer** [comment] 2019-01-15 03:07
Do we still see this issue at all @sudara? I have not seen anything in a while.
Should we close this ticket?

**Closed** 2019-06-06 19:52 UTC
Labels: bug, localhost
