### ISSUE TITLE
[Admin] Blocklist feature

### ISSUE THREAD

**Issue by innatewonderer** [sudara/alonetone#281] opened 2018-11-06 00:29 UTC
Per Sudara:
Re: Blocklist, might be best left for anohter PR. We'll need to create a table with ip (which can be a range or a full ip) and blocked_count and last_blocked_at (no need for created_at/updated_at) — right now there's a manual blocklist here https://github.com/sudara/alonetone/blob/master/app/concerns/prevent_abuse.rb#L2-L5
The idea is to turn that list into being database backed and we'd have to then a) change logic in the file to block plays by blocked ips and increment counter b) do the same for comments, user creation.

**Comment by sudara** [comment] 2018-11-06 22:02
Let me know if you want to hash this out together at some point. Thinking `blocked_ip`/`BlockedIp` would be a nice table/resource name...

**Comment by sudara** [comment] 2018-12-19 22:03
Duplicate of #249

**Comment by sudara** [comment] 2019-08-26 23:15
Duplicate of #249

**Closed by sudara** 2019-08-26 23:15 UTC
