### ISSUE TITLE
Do playlists need explicit publishing? 

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#677] opened 2019-08-19 19:52 UTC
An album can act private but without indication: create a Playlist, add tracks or not, but never explicitly click 'save' on the top form

**Comment by ofsound** [comment] 2019-08-19 19:58
As it is, getting the "Track Added!" confirmations might give the user some sense the playlist is ready to roll. And then them being able to navigate away from the page without getting stopped.

**Comment by sudara** [comment] 2019-08-20 19:16
Ok — so there are a few problems here, I think.

1) We need clear design to show *when* a playlist is private https://github.com/sudara/alonetone/issues/595

2) Playlists start out as private and need explicit publishing. Do we want to implicitly publish when enough tracks are added? Or do we want a UI element that appears that says "your playlist is now eligible for publishing" once there are two tracks?...

**Comment by sudara** [comment] 2019-08-26 23:45
Dupe of #690

**Closed by sudara** 2019-08-26 23:45 UTC
