### ISSUE TITLE
Uploading a new track gives it 1 listen even if you don't listen to it

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#786] opened 2019-09-24 19:54 UTC

**Comment by sudara** [comment] 2019-09-24 19:59
Maybe a duplicate of #741 — the single track player registers a listen on page load.

**Comment by ofsound** [comment] 2019-09-24 20:02
@sudara 

I'll close this one. I just had a sense that last week I uploaded some tracks and they sat at 0 for a while, but recently I've been noticing a play of my own! But yeah, who knows exactly :)

**Closed** 2019-09-24 20:02 UTC
