### ISSUE TITLE
Link Validation or more clear directions for external links on Edit Profile Page

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#1178] opened 2022-02-17 01:41 UTC
A user who otherwise has used the site with no issues, pasted too much into the youtube field.

<img width="447" alt="IMG_9526" src="https://user-images.githubusercontent.com/407724/154388048-d1ede95e-7bbb-4b22-9d6a-f7c9d7e7e503.png">

But made me think, for example, on iOS, it's quite difficult to select only part of a URL vs the entire URL?

Or maybe we could smartly strip the duplicate characters, or fire a warning if the resultant URL will definitely fail.

**Comment by sudara** [comment] 2022-02-22 17:37
Dupe of #1044.

We could get rid of the prefix entirely in the end if we think it takes up too much space on mobile and just adds confusion.

**Closed by sudara** 2022-02-22 17:37 UTC
