### ISSUE TITLE
macOS Safari maybe crashes when clicking a select input field in Edit Profile

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#808] opened 2019-09-30 22:40 UTC

**Comment by sudara** [comment] 2019-09-30 23:29
Safari Desktop? Works for me on iOS 13 and Safari 13.0.1

**Comment by ofsound** [comment] 2019-10-01 00:36
I restarted my computer,

on Safari Desktop 13.0.1, macOS 10.14.6 

It got stuck again at this state, and then Safari required a force quit:

<img width="401" alt="Screenshot 2019-09-30 18 35 48" src="https://user-images.githubusercontent.com/407724/65926175-26babe80-e3b1-11e9-9d90-0b2a67475247.png">

**Comment by sudara** [comment] 2019-12-18 14:14
Closing this until we see it again. Which sounds like maybe never if it's not reproducible on Catalina?...

**Closed by sudara** 2019-12-18 14:14 UTC
